title: "Andreas Orthey"
description: "Andreas Orthey's personal site showcases publications, podcasts, and insights into robotics. Connect and collaborate!"
version: 1.77

baseurl: ""
url: "https://aorthey.com"
canonical-url: "https://aorthey.com"

nav_enabled: true
nav_sort: case_sensitive # Capital letters sorted before lowercase
nav_error_report: true
back_to_top: true
back_to_top_text: "Back to top"

twitter_username: andreas_orthey
github_username:  aorthey
linkedin_username: aorthey
youtube_username: andreasorthey

plugins:
  - jekyll
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-favicon

minima:
  skin: auto

image:
  path: /assets/images/face_square.png
  height: 400
  width: 400
  alt: Andreas Orthey Picture

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/face_square.png

author:
  name: Andreas Orthey
  url: https://aorthey.com/
  picture: /assets/images/face_square.png
  twitter: andreas_orthey

include:
  - assets/pdf/
  - assets/bib/
  - assets/css/
  - assets/js/
  - assets/generate/

theme: minima

header_pages:
  - index.md
  - src/publications.md
  - src/talks.md
  - src/resources.md
  - src/podcast.md
  - src/about.md
