title: Andreas Orthey
description: "Andreas Orthey's personal site showcases publications, podcasts, and insights into robotics. Connect and collaborate!"

baseurl: ""
url: "https://aorthey.com"
canonical-url: "https://aorthey.com"

nav_enabled: true
nav_sort: case_sensitive # Capital letters sorted before lowercase
nav_error_report: true
back_to_top: true
back_to_top_text: "Back to top"

twitter_username: andreas_orthey
github_username:  aorthey
linkedin_username: aorthey
youtube_username: andreasorthey

plugins:
  - jekyll
  - jekyll-seo-tag
  - jekyll-sitemap

image:
  path: /assets/images/face-square.png
  height: 400
  width: 400

include:
  - assets/pdf/
  - assets/bib/
  - assets/css/
  - assets/js/
  - assets/generate/

theme: minima

header_pages:
  - index.md
  - src/podcast.md
  - src/publications.md
  - src/about.md
