title: Andreas Orthey
description: A simple website with information
theme: just-the-docs
#url: https://just-the-docs.github.io
url: "http://localhost:4000" # Adjust if deployed

baseurl: ""

nav_enabled: true
nav_sort: case_sensitive # Capital letters sorted before lowercase
nav_error_report: true
back_to_top: true
back_to_top_text: "Back to top"

plugins:
  - jekyll

include:
  - assets/
  - assets/css/
  - assets/js/
